services:
  db:
    image: postgres
    container_name: newfire
    environment:
      POSTGRES_PASSWORD: newfire
    ports:
      - "5432:5432"

  app:
    container_name: "app"
    build: .
    networks:
      - backend
    ports:
      - 8000:8000

networks:
  backend:
    driver: bridge
